# Generated by Django 5.0.6 on 2025-12-08 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_management', '0004_add_company_and_company_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama pengaturan (unique key)', max_length=200, unique=True)),
                ('label', models.CharField(help_text='Label untuk ditampilkan', max_length=200)),
                ('setting_type', models.CharField(choices=[('general', 'Pengaturan Umum'), ('notification', 'Notifikasi'), ('security', 'Keamanan'), ('email', 'Email'), ('integration', 'Integrasi'), ('backup', 'Backup'), ('other', 'Lainnya')], default='general', max_length=50)),
                ('value', models.TextField(blank=True, help_text='Nilai pengaturan', null=True)),
                ('value_type', models.CharField(default='text', help_text='Tipe nilai: text, number, boolean, json, email, url', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Deskripsi pengaturan', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Apakah pengaturan ini bisa diakses oleh non-admin?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['setting_type', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='fyppostvalue',
            options={'ordering': ['-post_date', '-viral_score', '-created_at'], 'verbose_name': 'FYP Post Value', 'verbose_name_plural': 'FYP Post Values'},
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='kpi_managem_created_dbd22d_idx',
            old_name='kpi_manage_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='kpi_managem_user_id_501c22_idx',
            old_name='kpi_manage_user_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='kpi_managem_action_0bf03a_idx',
            old_name='kpi_manage_action_idx',
        ),
        migrations.RenameIndex(
            model_name='company',
            new_name='kpi_managem_company_71e64c_idx',
            old_name='kpi_manage_company_idx',
        ),
        migrations.RenameIndex(
            model_name='company',
            new_name='kpi_managem_code_594f35_idx',
            old_name='kpi_manage_code_idx',
        ),
        migrations.RenameIndex(
            model_name='fyppostvalue',
            new_name='kpi_managem_viral_s_fb915f_idx',
            old_name='kpi_manage_viral_s_idx',
        ),
        migrations.RenameIndex(
            model_name='socialmediaaccount',
            new_name='kpi_managem_platfor_0f9e90_idx',
            old_name='kpi_manage_platform_idx',
        ),
        migrations.RenameIndex(
            model_name='socialmediaaccount',
            new_name='kpi_managem_owner_i_53fb7c_idx',
            old_name='kpi_manage_owner_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='socialmediaaccount',
            new_name='kpi_managem_account_77f103_idx',
            old_name='kpi_manage_account_idx',
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='auto_sync_enabled',
            field=models.BooleanField(default=False, help_text='Aktifkan auto sync dari API'),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='input_method',
            field=models.CharField(choices=[('manual', 'Manual Input'), ('api', 'API/Token Sync')], default='manual', help_text='Metode input: Manual atau API Sync', max_length=20),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='sync_schedule',
            field=models.CharField(blank=True, help_text='Jadwal sync (e.g., daily, weekly, hourly)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='kpi_target',
            field=models.JSONField(blank=True, default=dict, help_text='Target KPIs (reach, engagement, conversion) in JSON format'),
        ),
        migrations.AlterField(
            model_name='collabbrand',
            name='contact_person',
            field=models.CharField(help_text='PIC kontak', max_length=100),
        ),
        migrations.AlterField(
            model_name='collabbrand',
            name='contract_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Agreement value / kontrak', max_digits=12),
        ),
        migrations.AlterField(
            model_name='collabbrand',
            name='deliverables',
            field=models.TextField(help_text='List of deliverables (story, feed, reels, live session)'),
        ),
        migrations.AlterField(
            model_name='dailyfeedreels',
            name='target_post_date',
            field=models.DateTimeField(help_text='Target post date untuk scheduling'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='systemsettings',
            index=models.Index(fields=['name'], name='kpi_managem_name_8e85c8_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsettings',
            index=models.Index(fields=['setting_type', 'is_active'], name='kpi_managem_setting_8c7319_idx'),
        ),
    ]
