# Generated by Django 5.0.6 on 2025-12-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_management', '0005_systemsettings_alter_fyppostvalue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_url',
            field=models.URLField(blank=True, help_text='URL tautan campaign', null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='content_url',
            field=models.URLField(blank=True, help_text='URL tautan konten story', null=True),
        ),
    ]
